
package com.bulpros.integrations.auditlog.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BGeGovEventsServices", targetNamespace = "http://egov.bg/bes/ws/v1", wsdlLocation = "https://auditlog.egov.bg:9446/auditLog/RegisterEventSOAPPort?wsdl")
public class BGeGovEventsServices
    extends Service
{

    private final static URL BGEGOVEVENTSSERVICES_WSDL_LOCATION;
    private final static WebServiceException BGEGOVEVENTSSERVICES_EXCEPTION;
    private final static QName BGEGOVEVENTSSERVICES_QNAME = new QName("http://egov.bg/bes/ws/v1", "BGeGovEventsServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://auditlog.egov.bg:9446/auditLog/RegisterEventSOAPPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BGEGOVEVENTSSERVICES_WSDL_LOCATION = url;
        BGEGOVEVENTSSERVICES_EXCEPTION = e;
    }

    public BGeGovEventsServices() {
        super(__getWsdlLocation(), BGEGOVEVENTSSERVICES_QNAME);
    }

    public BGeGovEventsServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), BGEGOVEVENTSSERVICES_QNAME, features);
    }

    public BGeGovEventsServices(URL wsdlLocation) {
        super(wsdlLocation, BGEGOVEVENTSSERVICES_QNAME);
    }

    public BGeGovEventsServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BGEGOVEVENTSSERVICES_QNAME, features);
    }

    public BGeGovEventsServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BGeGovEventsServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegisterEventSOAPPort
     */
    @WebEndpoint(name = "RegisterEventSOAPPortImplPort")
    public RegisterEventSOAPPort getRegisterEventSOAPPortImplPort() {
        return super.getPort(new QName("http://egov.bg/bes/ws/v1", "RegisterEventSOAPPortImplPort"), RegisterEventSOAPPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterEventSOAPPort
     */
    @WebEndpoint(name = "RegisterEventSOAPPortImplPort")
    public RegisterEventSOAPPort getRegisterEventSOAPPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://egov.bg/bes/ws/v1", "RegisterEventSOAPPortImplPort"), RegisterEventSOAPPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BGEGOVEVENTSSERVICES_EXCEPTION!= null) {
            throw BGEGOVEVENTSSERVICES_EXCEPTION;
        }
        return BGEGOVEVENTSSERVICES_WSDL_LOCATION;
    }

}
