
package com.bulpros.integrations.auditlog.model;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegisterEventSOAPPort", targetNamespace = "http://egov.bg/bes/ws/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegisterEventSOAPPort {


    /**
     * 
     * @param eaServiceLCEvent
     */
    @WebMethod(operationName = "RegisterEvent")
    @Oneway
    @RequestWrapper(localName = "RegisterEvent", targetNamespace = "http://egov.bg/bes/ws/auditlog/v1", className = "com.bulpros.integrations.auditlog.model.RegisterEventType")
    public void registerEvent(
        @WebParam(name = "EAServiceLCEvent", targetNamespace = "http://egov.bg/bes/ws/auditlog/v1")
        List<EAServiceLCEventType> eaServiceLCEvent);

}
